### ISSUE TITLE
element "LDM" already exists

### ISSUE THREAD

**Issue by Kyle-Kyle** [Boyan-MILANOV/ropgenerator#18]
~~~
Traceback (most recent call last):
  File "/home/kylebot/.virtualenvs/ropgenerator/bin/ROPGenerator", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/kylebot/src/ropgenerator/ROPGenerator", line 3, in <module>
    import ropgenerator.main.Main as Main
  File "/home/kylebot/src/ropgenerator/ropgenerator/main/Main.py", line 6, in <module>
    from ropgenerator.main.Load import load, loaded_binary
  File "/home/kylebot/src/ropgenerator/ropgenerator/main/Load.py", line 19, in <module>
    from ropgenerator.main.Scanner import init_scanner, find_opcode
  File "/home/kylebot/src/ropgenerator/ropgenerator/main/Scanner.py", line 7, in <module>
    from ropgenerator.core.Architecture import *
  File "/home/kylebot/src/ropgenerator/ropgenerator/core/Architecture.py", line 1, in <module>
    from ropgenerator_core_ import\
ImportError: IROperation: element "LDM" already exists!
~~~

**Comment by Boyan-MILANOV** [comment]
Hey :) 
Thanks for reporting the issue, but I couldn't reproduce it on my side. 
Could you please provide some context, how did you install and launch ROPGenerator ? 

Boyan.

**Comment by Kyle-Kyle** [comment]
OS: 64bit linux
Python: 3.6.5
How I compile: change os.environ['CC']='clang' to 'gcc' and then follow README
How I launch: ROPGenerator in cmd

**Comment by SaneBow** [comment]
Same error here. Installed inside 64bit Ubuntu 16.04 docker. Compiled with clang.

**Comment by Boyan-MILANOV** [comment]
Ok so I could reproduce it on a clean VM. 
The bug came from a duplicate export of "LDM" in the python bindings. I'm not sure why it wasn't triggered before, probably recent changes in pybind11 unveiled it. 

The issue should be fixed now, let me know if it's working on your side and I'll close the issue :) 

Boyan.

**Comment by Kyle-Kyle** [comment]
It is fixed. Thanks!
