### ISSUE TITLE
Only starts with root account.

### ISSUE THREAD

**Issue by fraf0** [Boyan-MILANOV/ropgenerator#4]
Hi,

It's not possible for me to launch the program in user. Only possible with the root account (sudo).
I installed with sudo too, as it was not possible to do it in user.

```
$ ROPGenerator
Traceback (most recent call last):
  File "/usr/local/bin/ROPGenerator", line 4, in <module>
    __import__('pkg_resources').run_script('ropgenerator==1.1', 'ROPGenerator')
  File "/home/fraf/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/fraf/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/ropgenerator-1.1-py2.7.egg/EGG-INFO/scripts/ROPGenerator", line 3, in <module>
    import ropgenerator.Main as Main
  File "/usr/local/lib/python2.7/dist-packages/ropgenerator-1.1-py2.7.egg/ropgenerator/Main.py", line 5, in <module>
    from prompt_toolkit import PromptSession, ANSI
ImportError: cannot import name PromptSession
$
```

But the same import in user work:

```
$ python
Python 2.7.15+ (default, Aug 31 2018, 11:56:52)
[GCC 8.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from prompt_toolkit import PromptSession, ANSI
>>> 
$
```

Regards,

**Comment by Boyan-MILANOV** [comment]
Hey, 

To install as user both the following are working for me (on Ubuntu 18.04) : 
`python setup.py install --user`
`python setup.py install --prefix ~/.local`

What error do you get when installing without sudo? 

I just pushed a small update to avoid the "Couldn't setup ROPGenerator directory" error message that was triggered mistakenly when installing locally. 

 Boyan
